openapi: 3.0.0
servers: 
  - url: 'http://delilahrestoacamica.herokuapp.com'
info:
  description: Api para Delilah Resto
  version: 1.0.0
  title: Delilah Resto
paths:
  /products:
    get:
      tags:
        - users
        - admins
      summary: Ingresando los valores correctos, se obtiene los productos con
        descripcion y precio.
      responses:
        '200':
          description: Lista de productos
          $ref: '#/components/schemas/products'
        '403':
          description: dato ingresado invalido
    post:
      tags:
        - admins
      summary: agregar un prodructo
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/products'
      security:
        - JWTAuth: []
      responses:
        '201':
          description: Producto creado
        '401':
          description: error en valor colocado
  /products/{id}:
    get:
      tags:
        - users
        - admins
      summary: Ingresando los valores correctos, se obtiene los productos con descripcion y precio.
      parameters:
        - name: id
          in: path
          description:  ID del producto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: listado de productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products'
    put:
      tags:
        - admins
      summary: modificar un prodructo
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/products'
      parameters:
        - name: id
          in: path
          description:  ID del producto
          required: true
          schema:
            type: integer
            format: int64
      security:
        - JWTAuth: []
      responses:
        '201':
          description: Producto modificado
        '401':
          description: error en valor colocado
    delete: 
      tags:
        - admins
      summary: eliminar un prodructo
      parameters:
        - name: id
          in: path
          description:  ID del producto
          required: true
          schema:
            type: integer
            format: int64
      security:
        - JWTAuth: []
      responses:
        '201':
          description: Producto eliminado
        '401':
          description: error en valor ingresado
  /users:
    get:
      tags:
        - admins
      summary: Ingresando los valores correctos, se obtiene la lista de usuarios
      security:
        - JWTAuth: []
      responses:
        '200':
          description: listado de usuarios
          content:
            application/json:
              schema:
                type: array
                items: 
                $ref: '#/components/schemas/users'
        '404':
          description: 'no tiene los permisos para realizar esta acción'
    post:
      tags:
        - users
        - admins
      summary: Crear nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/users'
      responses:
        '201':
          description: Usuario creado
        '401':
          description: Error al crear el usuario
  /users/{id}:
    get:
      tags:
        - users
        - admins
      summary: Ingresando los valores correctos, se obtiene los datos del usuario
      parameters:
        - in: path
          name: id
          description: Ingrese su usuario
          example: "mcanzani"
          required: true
          schema: 
            type: string
      security:
        - JWTAuth: []      
      responses:
        '200':
          description: Detalle de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/users'
        '401':
          description: El token de acceso no se ha encontrado o es invalido.
        '404':
          description: usuario no encontrado
    patch:
      tags: 
        - users
        - admins
      parameters:
        - in: path
          name: id
          description: Ingrese su usuario
          example: "mcanzani"
          required: true
          schema: 
            type: string
      summary: modificar un usuario
      description:  Ingresar nombre de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/userupdate'
      security:
        - JWTAuth: []
      responses:
        '201':
          description: Usuario modificado
        '401':
          description: error en valor colocado
  /orders:
    get:
      tags:
        - admins
      summary: 'Ingresando los valores correctos, se obtiene la lista de pedidos'
      security:
        - JWTAuth: []
      responses:
        '200':
          description: listado de pedidos
          content:
            application/json:
              schema:
                type: string
                items: 
                  $ref: '#/components/schemas/orders'
        '400':
          description: error en valor colocado
    post:
      tags: 
      - users
      - admins
      summary: Crear nuevo pedido
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/orders'
      responses:
        '201':
          description: Pedido creado
        '401':
          description: error en valor colocado
  /orders/{id}:
    get:
      tags:
        - admins
      summary: 'Ingresando los valores correctos, se obtiene los datos del pedidos'
      parameters:
        - in: path
          name: id
          description: id del pedido
          required: true
          schema: 
            type: string
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Detalle de pedidos
        '401':
          description: El token de acceso no se ha encontrado o es invalido.
        '404':
          description: pedido no encontrado
    put:
      tags: 
      - admins
      summary: modificar un pedido
      parameters:
        - name: id
          in: path
          description:  ID del producto
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ordersupdate'
      security:
        - JWTAuth: []
      responses:
        '201':
          description: pedido modificado
        '401':
          description: error en valor colocado
    delete: 
      tags:
        - admins
      summary: eliminar una orden
      parameters:
        - name: id
          in: path
          description:  ID del producto
          required: true
          schema:
            type: integer
            format: int64
      security:
        - JWTAuth: []
      responses:
        '201':
          description: Orden eliminada
        '401':
          description: error en valor ingresado
  /login:
    post:
      tags:
        - admins
        - users
      summary: Login de usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/login'
      responses:
        '201':
          description: Usuario logueado
        '401':
          description: Usuario o contraseña invalida
        '409':
          description: El usuario no existe. 
components:
  securitySchemes:
    JWTAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    login: 
      type: object
      properties:
        usuario:
          type: string 
        password:
          type: string        
    products:
      type: object
      properties:
        nombre_plato:
          type: string
          example: Sandwich veggie
        detalle:
          type: string
          example: Sandwich de salmon con pan de harina de almendras.
        foto:
          type: string
          example: 'https://unsplash.com/photos/ddZYOtZUnBk'
        precio:
          type: integer
          format: int32
          example: 360
    users:
      type: object
      properties:
        usuario:
          type: string
        nombre:
          type: string
        apellido:
          type: string
        email:
          type: string
          example: test@test.com
        password:
          type: string
        telefono:
          type: integer
          format: int64
        direccion:
            type: string
    userupdate: 
      type: object
      properties:
        email:
          type: string
          example: test@test.com
        telefono:
          type: integer
          format: int64
        direccion:
            type: string    
    orders:
      type: object
      properties:
        producto_id:
          type: string
          example : [4,4,5]
        forma_de_depago:
          type: string
          enum: 
            - efectivo
            - tarjeta
    ordersupdate:
      type: object
      properties: 
        status: 
          enum:
          - confirmado
          - preparando
          - enviando
          - entregado
          example : "confirmado"